name: Man10Slot
version: ${project.version}
main: red.man10.man10slot.Man10Slot
commands:
  mslot:
    description: Command no setsumei
    usage: /<command>
    default: true
    permission:
      mslot.setting:
        default: OP
permissons:
  mslot.use:
    default: true